import ActiveSectionProvider from "@/context/activeSectionContext";
import "./globals.css";
import { Inter } from "next/font/google";
import ThemeContextProvider from "@/context/themeContext";
import { Toaster } from "react-hot-toast";
import ThemeSwitch from "@/components/themeSwitch";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Eddie | Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} pt-28 sm:pt-36 bg-gray-100 dark:bg-gray-700 dark:text-gray-300 text-gray-700 transition-all`}
      >
        <div className="bg-[#dbd7fb] absolute top-[-1rem] -z-10 left-[-35rem] h-[31.25rem] w-[50rem] rounded-full blur-[10rem] sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem] dark:bg-[#676394]"></div>
        <ThemeContextProvider>
          <ActiveSectionProvider>{children}</ActiveSectionProvider>
          <Toaster position="top-right" />
          <ThemeSwitch />
        </ThemeContextProvider>
      </body>
    </html>
  );
}
